config/urls.py
import debug_toolbar
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from users import views as user_views
from django.urls import path, include

urlpatterns = [
    path('', RedirectView.as_view(url='/login/', permanent=True)),
    path('admin/', admin.site.urls),
    path('phonebook/', include('phonebook.urls')),
    path('register/', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile_page, name='profile'),
    path('__debug__/', include(debug_toolbar.urls)),
]

phonebook/urls.py
from django.urls import path

from phonebook import views

app_name = 'phonebook'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:contact_id>', views.detail, name='detail'),
    path('add', views.create_contact, name='create_contact'),
    path('update/<int:contact_id>', views.update_contact, name='update_contact'),
    path('delete/<int:contact_id>', views.delete_contact, name='delete_contact'),
]

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.register, name='register'),
]

phonebook/models.py
from django.contrib.auth.models import User
from django.db import models


class Contact(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    company = models.CharField(max_length=250, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    address = models.CharField(max_length=250, null=True, blank=True)
    phone_number = models.CharField(max_length=30)

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

phonebook/forms.py
from django import forms

from phonebook.models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        exclude = ['user_id']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

phonebook/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from phonebook.forms import ContactForm
from phonebook.models import Contact


@login_required
def index(request):
    user = request.user
    contact_name = request.GET.get('contact_name')

    contacts_queryset = Contact.objects.filter(user=user).order_by('first_name')

    # search code
    if contact_name != '' and contact_name is not None:
        contacts = contacts_queryset.filter(first_name__icontains=contact_name).all()
    else:
        contacts = contacts_queryset.all()

    return render(request, 'phonebook/index.html', context={'contacts': contacts})


@login_required
def detail(request, contact_id):
    contact = Contact.objects.get(pk=contact_id)

    return render(request, 'phonebook/detail.html', context={'contact': contact})


@login_required
def create_contact(request):
    form = ContactForm(request.POST or None)

    if form.is_valid():
        form.save(commit=False)
        form.instance.user = request.user
        form.save()
        return redirect('phonebook:index')

    return render(request, 'phonebook/contact_form.html', {'form': form})


@login_required
def update_contact(request, contact_id):
    contact = Contact.objects.get(pk=contact_id)
    form = ContactForm(request.POST or None, instance=contact)

    if form.is_valid():
        form.save(commit=False)
        form.instance.user = request.user
        form.save()
        return redirect('phonebook:index')

    return render(request, 'phonebook/contact_form.html', {'form': form})


@login_required
def delete_contact(request, contact_id):
    contact = Contact.objects.get(pk=contact_id)

    if request.method == 'POST':
        contact.delete()
        return redirect('phonebook:index')

    return render(request, 'phonebook/delete.html', context={'contact': contact})

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import RegisterForm


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, account created')
            return redirect('profile')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile_page(request):
    return render(request, 'users/profile.html')

phonebook/templates/phonebook/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
              integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <title>Phonebook</title>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark">
            <a href="{% url 'phonebook:index' %}" class="navbar-brand">Phonebook</a>

            <div class="navbar">
                {% if user.is_authenticated %}
                    <a href="{% url 'phonebook:create_contact' %}" class="nav-item nav-link">Add Contact</a>
                    <a href="{% url 'profile' %}" class="nav-item nav-link">Profile</a>
                    <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
                {% endif %}
            </div>
        </nav>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

phonebook/templates/phonebook/contact_form.html
{% extends 'phonebook/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h1 class="mt-2">Add Contact</h1>
    <hr class="mt-0 mb-4">

    <form method="post" novalidate>
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.first_name|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.last_name|as_crispy_field }}
            </div>
        </div>
        {{ form.company|as_crispy_field }}
        {{ form.email|as_crispy_field }}
        {{ form.address|as_crispy_field }}
        {{ form.phone_number|as_crispy_field }}
        <button type="submit" class="btn btn-success">Save</button>
    </form>
{% endblock %}

phonebook/templates/phonebook/delete.html
{% extends 'phonebook/base.html' %}

{% block content %}
    <h1 class="mt-2">Delete Contact</h1>
    <hr class="mt-0 mb-4">

    <form method="POST">
        {% csrf_token %}
        <div class="text-center">
            <h5>Are you sure you want to delete this contact?</h5>
            <button type="submit" class="btn btn-danger">Delete Contact</button>
        </div>
    </form>
{% endblock %}

phonebook/templates/phonebook/detail.html
{% extends 'phonebook/base.html' %}

{% block content %}
    <h1 class="mt-2">Contact Details</h1>
    <hr class="mt-0 mb-4">

    <h4 class="text-center">{{ contact.first_name }} {{ contact.last_name }}</h4>

    <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <small class="text-muted">Company</small>
                <h6 class="my-0">{{ contact.company | default_if_none:'-' }}</h6>
            </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <small class="text-muted">Phone</small>
                <h6 class="my-0">{{ contact.phone_number }}</h6>
            </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <small class="text-muted">Email</small>
                <h6 class="my-0">{{ contact.email }}</h6>
            </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <small class="text-muted">Address</small>
                <h6 class="my-0">{{ contact.address | default_if_none:'-' }}</h6>
            </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <a href="{% url 'phonebook:update_contact' contact.id %}">Edit</a>
                <a href="{% url 'phonebook:delete_contact' contact.id %}">Delete</a>
            </div>
        </li>
    </ul>
{% endblock %}

phonebook/templates/phonebook/index.html
{% extends 'phonebook/base.html' %}

{% block content %}
    <h1 class="mt-2">My Contacts</h1>
    <hr class="mt-0 mb-4">

    <form class="input-group mb-3">
        <input type="search" name="contact_name" placeholder="Search for contacts"
               class="form-control borderless">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit">Search</button>
        </div>
    </form>

    <ul class="list-group">
        {% for contact in contacts %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <a href="{% url 'phonebook:detail'  contact.id %}" class="text-dark">
                    {{ contact.first_name }} {{ contact.last_name }}
                </a>
                <div>
                    <a href="{% url 'phonebook:update_contact' contact.id %}" class="mr-2">Edit</a>
                    <a href="{% url 'phonebook:delete_contact' contact.id %}" class="text-danger">Delete</a>
                </div>
            </li>

        {% endfor %}
    </ul>
{% endblock %}

users/templates/users/login.html
{% extends 'phonebook/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="card">
        <div class="card-header text-white bg-info">
            <div class="card-title">
                Login
            </div>
        </div>
        <div class="card-body">
            <form method="POST" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn-info" type="submit">Login</button>
            </form>
            <p class="card-text pt-3">
                Don't have an account? <a href="{% url 'register' %}">Sign up</a>
            </p>
        </div>
    </div>
{% endblock %}

users/templates/users/logout.html
<h1>You have been logged out</h1>

users/templates/users/profile.html
{% extends 'phonebook/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h1 class="mt-2">Welcome {{ user.username|upper }}</h1>
    <hr class="mt-0 mb-4">

{% endblock %}

    <nav class="navbar navbar-expand-sm bg-light">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a href="#" class="nav-link">Home</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'phonebook:index' %}" class="nav-link">My Contacts</a>
            </li>
        </ul>
        <ul class="navbar-nav justify-content-right">
            <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link">Logout</a>
            </li>
        </ul>
    </nav>

users/templates/users/register.html
{% extends 'phonebook/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="card">
        <div class="card-header text-white bg-info">
            <div class="card-title">
                Register
            </div>
        </div>
        <div class="card-body">
            <form method="POST" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn-info" type="submit">Signup</button>
            </form>
            <p class="card-text pt-3">
                Have an account? <a href="{% url 'login' %}">Log in</a>
            </p>
        </div>
    </div>
{% endblock %}